#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NAME="pdj-volumetric-macOS-arm64"
SOURCE_APP="$ROOT/volumetric/bin/volumetric.app"
DIST="$ROOT/dist/$NAME"
mkdir -p "$DIST"
make -C "$ROOT/volumetric"
ditto "$SOURCE_APP" "$DIST/volumetric.app"
mkdir -p "$DIST/volumetric.app/Contents/Resources/data"
ditto "$ROOT/volumetric/bin/data/shaders" "$DIST/volumetric.app/Contents/Resources/data/shaders"
ditto "$ROOT/docs/pdjv/fixtures/golden_v0.pdjv" "$DIST/volumetric.app/Contents/Resources/data/golden_v0.pdjv"
ditto "$ROOT/docs/pdjv/fixtures/golden_v1.pdjv" "$DIST/volumetric.app/Contents/Resources/data/golden_v1.pdjv"
cp "$ROOT/volumetric/bin/data/settings.json" "$DIST/volumetric.app/Contents/Resources/data/settings.json"
mkdir -p "$DIST/SuperCollider"
cp "$ROOT/supercollider/pdj_datamatics.scd" "$DIST/SuperCollider/"
cp "$ROOT/supercollider/pdj_volumetric_compat.scd" "$DIST/SuperCollider/"
cp "$ROOT/volumetric/README.md" "$DIST/README.md"
echo "Staged $DIST (no source video)."
